# 6. Installing Dependencies and Compiling Assets
sudo gem install bundler --version 2.3.26; 
bundle config set --local path vendor/bundle; 
bundle install; 
sudo gem update strscan; 
yarn install; 
mv db/migrate/20210823222355_change_immersive_reader_allowed_on_to_on.rb .; 
mv db/migrate/20210812210129_add_singleton_column.rb db/migrate/20111111214311_add_singleton_column.rb; 
yarn gulp rev; 
RAILS_ENV=production bundle exec rake db:initial_setup; 
mv 20210823222355_change_immersive_reader_allowed_on_to_on.rb db/migrate/.; 
RAILS_ENV=production bundle exec rake db:migrate; 
mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands; 
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss Gemfile.lock log/production.log; 
RAILS_ENV=production bundle exec rake canvas:compile_assets;