# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: DB_NAME
  host: DB_HOST
  username: DB_USERNAME
  password: DB_PASSWORD
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: DB_NAME
  password: DB_PASSWORD
  timeout: 5000
  secondary:
    replica: true
    username: canvas_readonly_user

production:
  adapter: postgresql
  encoding: utf8
  database: DB_NAME
  host: DB_HOST
  username: DB_USERNAME
  password: DB_PASSWORD
  timeout: 5000
