production: &default
  # replace this with a random string of at least 20 characters
  encryption_key: ENCRYPTION_KEY
  # lti_iss: 'https://dcctest.online'
  lti_iss: https://DOMAIN

development:
  <<: *default
  encryption_key: ENCRYPTION_KEY
  previous_encryption_keys:
    - 0610afc39c93010e4e6f41b8898ddd131a3ddcaf

test:
  <<: *default
  encryption_key: ENCRYPTION_KEY
