# standard vault config, including address of
# vault server as a string (addr) or in a file (addr_path)
# and path where vault token can
# be found (token_path) or the token itself (token)
# production:
#   addr_path: /path/to/vault/address
#   token_path: /path/to/vault/token
# test:
#   addr: "https://vault.test.domain"
#   token: s.wOrq9dO9kzOcuvB06CMviJhZ
# development:
#   addr: "https://vault.dev.domain"
#   token: s.wOrq9dO9kzOcuvB06CMviJhZ

# if you don't want to run vault, you can make use
# of a "vault_contents.yml" file in this directory and
# specify "file" as both your addr and token_path.
# this will make Canvas Vault read from the file
# contents rather than trying to talk to a vault agent.
development:
  addr: file
  token: file
test:
  addr: file
  token: file
production:
  'sts/testaccount/sts/canvas-shards-lookupper-dev':
    access_key: 'fake-access-key'
    secret_key: 'fake-secret-key'
    security_token: 'fake-security-token'
  'sts/testaccount/sts/canvas-release-notes':
    access_key: 'fake-access-key'
    secret_key: 'fake-secret-key'
    security_token: 'fake-security-token'
  'app-canvas/data/secrets':
    data:
      canvas_security:
        encryption_secret: "YOUR_ECOSYSTEM_SECRET"
        signing_secret: "YOURECOSYSTEM_SECRET"